### PR TITLE
Make SystemFS checks more specific

### PR DESCRIPTION
**Pull request by Fayti1703**
This fixes a few compatibility issues with BLT4L, as before, the mod would simply refuse to load due to an attempt to call a nil value.

### CODE REVIEW

**Comment by Luffyyy** [comment]
May I know why there are some functions and not all of them in the Linux version?

**Comment by Luffyyy** [comment]
Also, it would be great if Linux users would report if there's anything wrong, I don't have time to install it myself and do these checks.

**Comment by Fayti1703** [comment]
I'm not sure myself, last time I checked it's actually the case that the SystemFS table exists, but it only contains one key, "exists" which is just nil. I'm really not the person to talk to here.

**Comment by Luffyyy** [comment]
Weird

**Pull request merged**
