### PR TITLE
Create swedish.txt

### PR DESCRIPTION
**Pull request by BreakinBenny**
Swedish translation by me.

### CODE REVIEW

**Comment by Luffyyy** [comment]
thanks.

**Comment by Luffyyy** [comment]
wait wait wait
WHY DID YOU PUSH TO DEV

**Comment by Luffyyy** [comment]
welp, you'll need to recreate it for master.

**Comment by BreakinBenny** [comment]
I did it because I realized that you might wanna do some updating in the dev branch before you made the Swedish localization official. Oh well, I'll put the localization in the master branch then.

**Pull request merged**
