### PR TITLE
Enable Heat for custom heists

### PR DESCRIPTION
**Pull request by MiamiCenterPL**
If you don't know what is Heat, it's this: https://i.imgur.com/Qsreape.png (random XP bonuses)
I was testing it for a couple of days - works just fine, no crashes.

### CODE REVIEW

**Comment by segabl** [comment]
I feel like this should be global option for BeardLib or exposed to the narrative module, as some people may not like getting heat bonuses for custom heists. I for instance have a lot of dummy or test maps where the heat bonus would get wasted on with no way to get rid of it.

**Comment by MiamiCenterPL** [comment]
> I feel like this should be global option for BeardLib or exposed to the narrative module, as some people may not like getting heat bonuses for custom heists. I for instance have a lot of dummy or test maps where the heat bonus would get wasted on with no way to get rid of it.

First of all, custom heists are crashing while this setting is off and player has some Heat filter stuff installed.
`Application has crashed: C++ exception
[string "lib/managers/jobmanager.lua"]:502: attempt to compare nil with number

SCRIPT STACK

heat_to_experience_multiplier() lib/managers/jobmanager.lua:523
get_job_heat_text() @mods/WolfHUD-master/lua/ContractHeat.lua:43
original() @mods/WolfHUD-master/lua/ContractHeat.lua:12
init() @mods/base/req/core/Hooks.lua:288
new() core/lib/utils/coreclass.lua:35
_setup_jobs() lib/managers/menu/contractbrokergui.lua:1115
_setup_change_filter() lib/managers/menu/contractbrokergui.lua:161
lib/managers/menu/contractbrokergui.lua:1337
run_return_on_all_live_components() lib/managers/menu/menucomponentmanager.lua:349
mouse_clicked() lib/managers/menu/menucomponentmanager.lua:1790
mouse_click() lib/managers/menu/menurenderer.lua:405
lib/managers/mousepointermanager.lua:369

Callstack:

     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     zip_get_name                                        
                     ntdll  (???)     RtlAllocateHeap                                     
Current thread: Main`

Secondly - If you want to disable the heat, you can just do it in heist's main.xml by setting the;
`ignore_heat="true"` in the `narrative` module, like this;
`<narrative contact="shinobi" icon="levels/mods/Xanax/textures/cr_brokericon" id="YouAreNeverAloneInTheDark" is_custom="true" jc="30" ignore_heat="true">`

**Comment by segabl** [comment]
There have been changes to the job code so most mods changing something about this crash if they havent been updated so I dont see this as relevant for this. Ignore heat should probably be true by default then to keep consistent behavior witht he current version. Or the default being affected by a BeardLib option.

**Comment by MiamiCenterPL** [comment]
When I was making this commit, I was thinking that every released heist by overkill has Heat enabled. There's already an option to disable that in main.xml for heists you don't want to have heat enabled for. Most of the map makers probably didn't even knew the Heat was disabled for all custom heists by default (me included)
When I spoke with Luffy about it, all he said is that he didn't even know what heat was used for when he was writting the code, and thus he disabled it by default.
I would opt for making it enabled by default anyways, to better match Overkill heists.
Although it's up to you what direction you're going with it. You can include an option to set default heat value in BeardLib for heists that doesn't have this setting in their main.xml
For now, I am going to manually enable heat for all my heists.

**Pull request closed without merging**
