### PR TITLE
Fixed a bug with glove variant DLC unlocking if your save is relatively new.

### PR DESCRIPTION
**Pull request by connieprice**
Also found an alternative solution to another section that let me remove some function overriding.
Also added locked status inheriting so that glove variants are properly locked if the glove is locked.

### CODE REVIEW

**Comment by Luffyyy** [comment]
Still worked on?

**Comment by connieprice** [comment]
Yeah, sorry for any confusion, more stuff cropped up that I want to push into the merge.

**Comment by connieprice** [comment]
Not gonna be able to finish the other stuff I wanted to push in.

**Comment by Luffyyy** [comment]
ig

**Pull request merged**
